# Generated by Django 6.1 on 2026-08-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
